DECLARE

BEGIN
    FOR OBJECT IN (SELECT * FROM USER_OBJECTS WHERE NOT USER_OBJECTS.OBJECT_NAME LIKE 'BIN$%')
        LOOP
            IF OBJECT.OBJECT_TYPE = 'TABLE' THEN
                DBMS_OUTPUT.PUT_LINE('DROP TABLE: ' || OBJECT.OBJECT_NAME);
                EXECUTE IMMEDIATE 'DROP TABLE ' || OBJECT.OBJECT_NAME || ' CASCADE CONSTRAINTS';
            ELSIF OBJECT.OBJECT_TYPE IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'PACKAGE', 'SEQUENCE', 'TYPE') THEN
                DBMS_OUTPUT.PUT_LINE('DROP ' || OBJECT.OBJECT_TYPE || ': ' || OBJECT.OBJECT_NAME);
                EXECUTE IMMEDIATE 'DROP ' || OBJECT.OBJECT_TYPE || ' ' || OBJECT.OBJECT_NAME;
            ELSE
                DBMS_OUTPUT.PUT_LINE('UNKNOWN TYPE: "' || OBJECT.OBJECT_TYPE || '" OF OBJECT ' || OBJECT.OBJECT_NAME);
            END IF;
        END LOOP;

    DBMS_OUTPUT.PUT_LINE('PURGE RECYCLEBIN');
    EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
END;
