-- TABLE: S_CUSTOMER
INSERT ALL
    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (201, 'Unisports', '55-2066101', '72 Via Bahia', 'Sao Paolo', NULL, 'Brazil', NULL, 'EXCELLENT', 12, 2,
            'Customer usually orders large amounts and has a high order total. This is okay as long')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (202, 'Simms Atheletics', '8 1-20101', '6741 Takashi Blvd.', 'Osaka', NULL, 'Japan', NULL, 'POOR', 14, 4,
            'Customer should always pay by cash until his credit rating improves.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (203, 'Delhi Sports', '91-10351', '11368 Chanakya', 'New Delhi', NULL, 'India', NULL, 'GOOD', 14, 4,
            'Customer specializes in baseball equipment and is the largest retailer in India.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (204, 'Womansport', '1-206-104-0103', '281 King Street', 'Seattle', NULL, 'USA', '98 101', 'EXCELLENT', 11, 1, NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (205, 'Kams Sporting Goods', '852-3692888', '15 Henessey Road', 'Hong Kong', NULL, NULL, NULL, 'EXCELLENT', 15, 4, NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (206, 'Sportique', '33-2257201', '172 Rue de Rivoli', 'Cannes', NULL, 'France', NULL, 'EXCELLENT', 15, 5,
            'Customer specializes in Soccer. Likes to order accessories in bright colors.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (207, 'Sweet Rock Sports', '234-6036201', '6 Saint Antoine', 'Lagos', NULL, 'Nigeria', NULL, 'GOOD', NULL, 3, NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (208, 'Muench Sports', '49-527454', '435 Gruenestrasse', 'Stuttgart', NULL, 'Germany', NULL, 'GOOD', 15, 5,
            'Customer usually pays small orders by cash and large orders on credit.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (209, 'Beisbol Si!', '809-352689', '792 Playa Del Mar', 'Sen Pedro de Macons', NULL, 'Dominican Republic', NULL, 'EXCELLENT', 11, 1,
            NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (210, 'Futbol Sonora', '52-404562', '3 Via Saguaro', 'Nogales', NULL, 'Mexico', NULL, 'EXCELLENT', 12, 2,
            'Customer is difficult to reach by phone. Try mail.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (211, 'Kuhns Sports', '42-111292', '7 Modrany', 'Prague', NULL, 'Czechoslovakia', NULL, 'EXCELLENT', 15, 5, NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (212, 'Hamada Sport', '20-1209211', '57A Corniche', 'Alexandria', NULL, 'Egypt', NULL, 'EXCELLENT', 13, 3,
            'Customer orders sea and water equipment.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (213, 'Big Johns Sports Emporium', '1-415-555-6281', '4783 18th Street', 'San Fracisco', NULL, 'USA', '94117', 'EXCELLENT', 11, 1,
            'Customer has a dependable credit record.')

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (214, 'Ojibvay Retail', '1-716-555-7171', '415 Main Street', 'Buffalo', NULL, 'USA', '14202', 'POOR', 11, 1, NULL)

    INTO S_CUSTOMER (ID, NAME, PHONE, ADDRESS, CITY, STATE, COUNTRY, ZIP_CODE, CREDIT_RATING, SALES_REP_ID, REGION_ID, COMMENTS)
    VALUES (215, 'Sporta Russia', '7-3892456', '6000 Yekatamina', 'Saint Petersburg', NULL, 'Russia', NULL, 'POOR', 15, 5,
            'This customer is very friendly, but has difficulty paying bills. Insist upon cash.')
(SELECT * FROM DUAL);


-- TABLE: S_DEPT
INSERT ALL
    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (10, 'Finance', 1)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (31, 'Sales', 1)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (32, 'Sales', 2)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (33, 'Sales', 3)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (34, 'Sales', 4)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (35, 'Sales', 5)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (41, 'Operations', 1)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (42, 'Operations', 2)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (43, 'Operations', 3)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (44, 'Operations', 4)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (45, 'Operations', 5)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (50, 'Administration', 1)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (11, 'Finance', 2)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (61, 'Accounting', 2)

    INTO S_DEPT (ID, NAME, REGION_ID)
    VALUES (54, 'Education', 1)
(SELECT * FROM DUAL);


-- TABLE: S_EMP
INSERT ALL
    INTO S_EMP
    VALUES (1, 'Velasquez', 'Carmen', 'cvelasqu', TO_DATE('3.03.1990', 'dd.mm.yyyy'), NULL, NULL, 'President', 32, 2550, NULL)

    INTO S_EMP
    VALUES (2, 'Ngao', 'LaDoris', 'lngao', TO_DATE('8.03.1990', 'dd.mm.yyyy'), NULL, 1, 'VP, Operations', 54, 1450, NULL)

    INTO S_EMP
    VALUES (3, 'Nagayamn', 'Midori', 'mnagayam', TO_DATE('17.06.1991', 'dd.mm.yyyy'), NULL, 1, 'VP, Sales', 31, 1400, NULL)

    INTO S_EMP
    VALUES (4, 'Quick-To-See', 'Mark', 'mquickto', TO_DATE('7.04.1990', 'dd.mm.yyyy'), NULL, 1, 'VP, Finance', 10, 1450, NULL)

    INTO S_EMP
    VALUES (5, 'Ropeburn', 'Audry', 'aropebur', TO_DATE('4.03.1990', 'dd.mm.yyyy'), NULL, 1, 'VP, Administration', 50, 1550, NULL)

    INTO S_EMP
    VALUES (6, 'Urguhart', 'Molly', 'murguhar', TO_DATE('18.01.1991', 'dd.mm.yyyy'), NULL, 2, 'Warehouse Manager', 41, 1200, NULL)

    INTO S_EMP
    VALUES (7, 'Menchu', 'Robertn', 'rmenchu', TO_DATE('14.05.1990', 'dd.mm.yyyy'), NULL, 2, 'Warehouse Manager', 42, 1250, NULL)

    INTO S_EMP
    VALUES (8, 'Biri', 'Ben', 'bbiri', TO_DATE('7.04.1990', 'dd.mm.yyyy'), NULL, 2, 'Warehouse Manager', 43, 1100, NULL)

    INTO S_EMP
    VALUES (9, 'Catchpole', 'Antoinette', 'acatchpo', TO_DATE('9.02.1992', 'dd.mm.yyyy'), NULL, 2, 'Warehouse Manager', 44, 1300, NULL)

    INTO S_EMP
    VALUES (10, 'Havel', 'Marta', 'mhavel', TO_DATE('27.02.1991', 'dd.mm.yyyy'), NULL, 2, 'Warehouse Manager', 45, 1307, NULL)

    INTO S_EMP
    VALUES (11, 'Magee', 'Colin', 'cmagee', TO_DATE('14.05.1990', 'dd.mm.yyyy'), NULL, 3, 'Sales Representative', 31, 1400, 10)

    INTO S_EMP
    VALUES (13, 'Sedeghi', 'Yasmin', 'ysedeghi', TO_DATE('18.02.1991', 'dd.mm.yyyy'), NULL, 3, 'Sales Representative', 33, 1515, 10)

    INTO S_EMP
    VALUES (14, 'Nguyen', 'Mai', 'mnguyen', TO_DATE('22.01.1992', 'dd.mm.yyyy'), NULL, 3, 'Sales Representative', 34, 1525, 15)

    INTO S_EMP
    VALUES (16, 'Maduro', 'Elena', 'emaduro', TO_DATE('7.02.1992', 'dd.mm.yyyy'), NULL, 6, 'Stock Clerk', 41, 1400, NULL)

    INTO S_EMP
    VALUES (17, 'Smith', 'George', 'gsmith', TO_DATE('8.03.1990', 'dd.mm.yyyy'), NULL, 6, 'Stock Clerk', 41, 940, NULL)

    INTO S_EMP
    VALUES (18, 'Nozaki', 'Akira', 'anozaki', TO_DATE('9.02.1991', 'dd.mm.yyyy'), NULL, 7, 'Stock Clerk', 42, 1200, NULL)

    INTO S_EMP
    VALUES (19, 'Patel', 'Vikram', 'vpatel', TO_DATE('6.08.1991', 'dd.mm.yyyy'), NULL, 7, 'Stock Clerk', 42, 795, NULL)

    INTO S_EMP
    VALUES (20, 'Newman', 'Chad', 'cnewman', TO_DATE('21.07.1991', 'dd.mm.yyyy'), NULL, 8, 'Stock Clerk', 43, 750, NULL)

    INTO S_EMP
    VALUES (21, 'Markarian', 'Alexander', 'amarkari', TO_DATE('26.05.1991', 'dd.mm.yyyy'), NULL, 8, 'Stock Clerk', 43, 850, NULL)

    INTO S_EMP
    VALUES (22, 'Chang', 'Eddie', 'echang', TO_DATE('30.11.1990', 'dd.mm.yyyy'), NULL, 9, 'Stock Clerk', 44, 800, NULL)

    INTO S_EMP
    VALUES (23, 'Patel', 'Radha', 'rpatel', TO_DATE('17.10.1990', 'dd.mm.yyyy'), NULL, 9, 'Stock Clerk', 34, 795, NULL)

    INTO S_EMP
    VALUES (24, 'Dancs', 'Bela', 'bdancs', TO_DATE('17.03.1991', 'dd.mm.yyyy'), NULL, 10, 'Stock Clerk', 45, 860, NULL)

    INTO S_EMP
    VALUES (25, 'Schwart,z', 'Sylvie', 'sschwart', TO_DATE('9.05.1991', 'dd.mm.yyyy'), NULL, 10, 'Stock Clerk', 45, 1100, NULL)
(SELECT * FROM DUAL);


-- TABLE: S_IMAGE
INSERT ALL
    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1480, 'JTIFF', 'Y', 'cabbat.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1482, 'JTIFF', 'Y', 'pucbat.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1486, 'JTIFF', 'Y', 'winbat.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1001, 'JTIFF', 'Y', 'bunboot.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1002, 'JTIFF', 'Y', 'aceboot.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1003, 'JTIFF', 'Y', 'proboot.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1011, 'JTIFF', 'Y', 'bunpole.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1012, 'JTIFF', 'Y', 'acepole.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1013, 'JTIFF', 'Y', 'propole.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1291, 'JTIFF', 'Y', 'gpbike.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1296, 'JTIFF', 'Y', 'himbike.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1829, 'JTIFF', 'Y', 'safthelm.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1381, 'JTIFF', 'Y', 'probar.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1382, 'JTIFF', 'Y', 'curlbar.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1119, 'JTIFF', 'Y', 'baseball.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1223, 'JTIFF', 'Y', 'chaphelm.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1367, 'JTIFF', 'Y', 'grglove.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1368, 'JTIFF', 'Y', 'alglove.tif', NULL)

    INTO S_IMAGE (ID, FORMAT, USE_FILENAME, FILENAME, IMAGE)
    VALUES (1369, 'JTIFF', 'Y', 'stglove.tif', NULL)
(SELECT * FROM DUAL);


-- TABLE: S_INVENTORY
INSERT ALL
    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10011, 101, 650, 625, 1100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10012, 101, 600, 560, 1000, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10012, 10501, 300, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10013, 101, 400, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10013, 10501, 314, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10021, 101, 500, 425, 740, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10022, 101, 300, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10022, 10501, 502, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10023, 101, 400, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10023, 10501, 500, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 101, 993, 625, 1000, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 201, 220, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 10501, 150, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 101, 700, 700, 1225, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 201, 166, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 10501, 222, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 101, 802, 800, 1400, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 201, 320, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 10501, 275, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 101, 1389, 850, 1400, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 201, 175, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 301, 69, 40, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 401, 88, 50, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 10501, 57, 50, 87, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 101, 850, 850, 1450, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 201, 162, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 301, 28, 20, 50, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 401, 75, 75, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 10501, 62, 50, 87, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 101, 2000, 1500, 2500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 201, 96, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 301, 85, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 401, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 10501, 194, 150, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 101, 2100, 2000, 3500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 201, 147, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 401, 113, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 10501, 277, 250, 440, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 101, 1822, 1800, 3150, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 201, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 301, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 401, 85, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 10501, 190, 150, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 101, 2250, 2000, 3500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 201, 200, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 401, 135, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 10501, 423, 250, 450, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 101, 650, 600, 1050, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 201, 130, 130, 230, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 301, 35, 20, 35, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 401, 0, 100, 175, 'A defective shipment was sent', '7-СЕН-2092')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 10501, 273, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 101, 2120, 1250, 2200, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 201, 180, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 301, 102, 95, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 401, 135, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 10501, 280, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 101, 505, 500, 875, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 201, 132, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 301, 57, 50, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 401, 250, 150, 250, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 10501, 288, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 101, 578, 350, 600, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 301, 70, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 401, 47, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 10501, 97, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 101, 0, 350, 600, 'Phenomenal sales...', '8-ФЕВ-2093')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 301, 65, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 401, 50, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 10501, 90, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 101, 250, 250, 437, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 301, 59, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 401, 80, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 10501, 151, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 101, 471, 450, 750, '  ', NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 301, 61, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 401, 91, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 10501, 224, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 101, 501, 450, 750, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 301, 49, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 401, 169, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 10501, 157, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 101, 400, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 301, 50, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 401, 100, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 10501, 159, 140, 24, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 101, 2530, 1500, 2600, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 201, 225, 220, 385, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 401, 240, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50273, 101, 233, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50273, 201, 75, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 101, 518, 500, 875, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 201, 82, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 401, 130, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 101, 244, 100, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 201, 98, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 401, 156, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 101, 230, 120, 310, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 201, 77, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 401, 151, 150, 280, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 101, 669, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 201, 62, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 401, 119, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 101, 0, 100, 175, 'Wait for Spring.', '12-АПР-2093')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 201, 67, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 401, 233, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 101, 173, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 201, 97, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 401, 138, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10011, 101, 650, 625, 1100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10012, 101, 600, 560, 1000, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10012, 10501, 300, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10013, 101, 400, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10013, 10501, 314, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10021, 101, 500, 425, 740, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10022, 101, 300, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10022, 10501, 502, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10023, 101, 400, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (10023, 10501, 500, 300, 525, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 101, 993, 625, 1000, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 201, 220, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20106, 10501, 150, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 101, 700, 700, 1225, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 201, 166, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20108, 10501, 222, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 101, 802, 800, 1400, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 201, 320, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20201, 10501, 275, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 101, 1389, 850, 1400, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 201, 175, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 301, 69, 40, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 401, 88, 50, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20510, 10501, 57, 50, 87, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 101, 850, 850, 1450, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 201, 162, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 301, 28, 20, 50, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 401, 75, 75, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (20512, 10501, 62, 50, 87, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 101, 2000, 1500, 2500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 201, 96, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 301, 85, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 401, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30321, 10501, 194, 150, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 101, 2100, 2000, 3500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 201, 147, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 401, 113, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30326, 10501, 277, 250, 440, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 101, 1822, 1800, 3150, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 201, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 301, 102, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 401, 85, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30421, 10501, 190, 150, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 101, 2250, 2000, 3500, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 201, 200, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 401, 135, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30426, 10501, 423, 250, 450, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 101, 650, 600, 1050, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 201, 130, 130, 230, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 301, 35, 20, 35, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 401, 0, 100, 175, 'A defective shipment was sent', '7-СЕН-2092')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (30433, 10501, 273, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 101, 2120, 1250, 2200, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 201, 180, 150, 260, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 301, 102, 95, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 401, 135, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32779, 10501, 280, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 101, 505, 500, 875, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 201, 132, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 301, 57, 50, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 401, 250, 150, 250, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (32861, 10501, 288, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 101, 578, 350, 600, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 301, 70, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 401, 47, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40421, 10501, 97, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 101, 0, 350, 600, 'Phenomenal sales...', '8-ФЕВ-2093')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 301, 65, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 401, 50, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (40422, 10501, 90, 80, 140, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 101, 250, 250, 437, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 301, 59, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 401, 80, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41010, 10501, 151, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 101, 471, 450, 750, '  ', NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 301, 61, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 401, 91, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41020, 10501, 224, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 101, 501, 450, 750, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 301, 49, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 401, 169, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41050, 10501, 157, 140, 245, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 101, 400, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 301, 50, 40, 70, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 401, 100, 70, 220, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (41080, 10501, 159, 140, 24, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 101, 2530, 1500, 2600, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 201, 225, 220, 385, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50169, 401, 240, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50273, 101, 233, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50273, 201, 75, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 101, 518, 500, 875, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 201, 82, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50417, 401, 130, 120, 210, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 101, 244, 100, 275, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 201, 98, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50418, 401, 156, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 101, 230, 120, 310, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 201, 77, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50419, 401, 151, 150, 280, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 101, 669, 400, 700, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 201, 62, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50530, 401, 119, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 101, 0, 100, 175, 'Wait for Spring.', '12-АПР-2093')

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 201, 67, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50532, 401, 233, 200, 350, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 101, 173, 100, 175, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 201, 97, 60, 100, NULL, NULL)

    INTO S_INVENTORY (PRODUCT_ID, WAREHOUSE_ID, AMOUNT_IN_STOCK, REORDER_POINT, MAX_IN_STOCK, OUT_OF_STOCK_EXPLANATION, RESTOCK_DATE)
    VALUES (50536, 401, 138, 100, 175, NULL, NULL)
(SELECT * FROM DUAL);


-- TABLE: S_ITEM
INSERT ALL
    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (97, 1, 20106, 9, 1000, 1000)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (97, 2, 30321, 1500, 50, 50)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (98, 1, 40421, 85, 7, 7)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (99, 1, 20510, 9, 18, 18)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (99, 2, 20512, 8, 25, 25)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (99, 3, 50417, 80, 53, 53)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (99, 4, 50530, 45, 69, 69)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 1, 10011, 135, 500, 500)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 2, 10013, 380, 400, 400)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 3, 10021, 14, 500, 500)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 4, 10023, 36, 400, 400)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 5, 30326, 582, 600, 600)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 6, 30433, 20, 450, 450)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (100, 7, 41010, 8, 250, 250)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 1, 30421, 16, 15, 15)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 2, 40422, 50, 30, 30)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 3, 41010, 8, 20, 20)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 4, 41100, 45, 35, 35)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 6, 50417, 80, 27, 27)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (101, 7, 50530, 45, 50, 50)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (102, 4, 20108, 28, 100, 100)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (102, 2, 20201, 123, 45, 45)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (103, 4, 30433, 20, 15, 15)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (103, 2, 32779, 7, 11, 11)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (104, 4, 20510, 9, 7, 7)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (104, 2, 20512, 8, 12, 12)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (104, 3, 30321, 1669, 19, 19)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (104, 4, 30421, 16, 35, 35)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (105, 2, 50419, 80, 13, 13)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (105, 3, 50532, 47, 28, 28)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (106, 1, 20108, 28, 46, 46)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (106, 2, 20201, 123, 21, 21)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (106, 5, 50418, 75, 98, 98)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (106, 6, 50419, 80, 27, 27)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (107, 1, 20106, 11, 50, 50)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (107, 2, 20108, 28, 22, 22)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (107, 3, 20201, 115, 130, 130)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (107, 4, 30321, 1669, 75, 75)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (107, 5, 30421, 16, 55, 55)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 1, 20510, 9, 9, 9)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 2, 20512, 8, 18, 18)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 3, 30321, 1669, 85, 85)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 4, 32779, 7, 60, 60)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 5, 32681, 60, 57, 57)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 6, 41080, 35, 50, 50)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (108, 4, 41100, 45, 42, 42)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (109, 4, 10011, 140, 150, 150)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (109, 2, 10012, 175, 600, 600)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (109, 1, 30326, 582, 1500, 1500)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (109, 6, 32681, 60, 50, 50)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (109, 7, 50418, 75, 43, 43)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (110, 2, 50536, 50, 23, 23)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (111, 1, 40421, 65, 27, 27)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (111, 2, 41080, 35, 29, 29)

    INTO S_ITEM (ORD_ID, ITEM_ID, PRODUCT_ID, PRICE, QUANTITY, QUANTITY_SHIPPED)
    VALUES (112, 1, 20106, 11, 50, 50)
(SELECT * FROM DUAL);


-- TABLE: S_ORD
INSERT ALL
    INTO S_ORD
    VALUES (100, 204, TO_DATE('31.08.1992', 'dd.mm.yyyy'), TO_DATE('10.09.1992', 'dd.mm.yyyy'), 11, 601100, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (102, 206, TO_DATE('1.09.1992', 'dd.mm.yyyy'), TO_DATE('8.09.1992', 'dd.mm.yyyy'), 15, 8335, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (103, 208, TO_DATE('2.09.1992', 'dd.mm.yyyy'), TO_DATE('22.09.1992', 'dd.mm.yyyy'), 15, 377, 'CASH', NULL)

    INTO S_ORD
    VALUES (104, 208, TO_DATE('3.09.1992', 'dd.mm.yyyy'), TO_DATE('23.09.1992', 'dd.mm.yyyy'), 15, 32430, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (106, 210, TO_DATE('7.09.1992', 'dd.mm.yyyy'), TO_DATE('15.09.1992', 'dd.mm.yyyy'), 12, 15634, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (107, 211, TO_DATE('7.09.1992', 'dd.mm.yyyy'), TO_DATE('21.09.1992', 'dd.mm.yyyy'), 15, 142171, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (108, 212, TO_DATE('7.09.1992', 'dd.mm.yyyy'), TO_DATE('10.09.1992', 'dd.mm.yyyy'), 13, 149570, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (109, 213, TO_DATE('8.09.1992', 'dd.mm.yyyy'), TO_DATE('28.09.1992', 'dd.mm.yyyy'), 11, 1020935, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (111, 204, TO_DATE('9.09.1992', 'dd.mm.yyyy'), TO_DATE('21.09.1992', 'dd.mm.yyyy'), 11, 2770, 'CASH', NULL)

    INTO S_ORD
    VALUES (97, 201, TO_DATE('28.08.1992', 'dd.mm.yyyy'), TO_DATE('17.09.1992', 'dd.mm.yyyy'), 12, 84000, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (98, 202, TO_DATE('31.08.1992', 'dd.mm.yyyy'), TO_DATE('10.09.1992', 'dd.mm.yyyy'), 14, 595, 'CASH', NULL)

    INTO S_ORD
    VALUES (99, 203, TO_DATE('31.08.92', 'dd.mm.yyyy'), TO_DATE('18.09.92', 'dd.mm.yyyy'), 14, 7707, 'CREDIT', NULL)

    INTO S_ORD
    VALUES (112, 210, TO_DATE('31.08.1992', 'dd.mm.yyyy'), TO_DATE('10.09.1992', 'dd.mm.yyyy'), 12, 550, 'CREDIT', NULL)
(SELECT * FROM DUAL);


-- TABLE: S_PRODUCT
INSERT ALL
    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (10012, 'Ace Ski Boot', 'Intermediate ski boot', 519, 1002, 200, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (10013, 'Pro Ski Boot', 'Advanced ski boot', 520, 1003, 410, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (20106, 'Junior Soccer Ball', 'Junior soccer ball', 613, NULL, 11, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (10011, 'Bunny Boot', 'Beginners ski boot', 518, 1001, 150, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (20108, 'World Cup Soccer Ball', 'World cup soccer ball', 615, NULL, 28, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (20201, 'World Cup Net', 'World cup net', 708, NULL, 123, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (20510, 'Black Hawk Knee Pads', 'Knee pads, pair', 1017, NULL, 9, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (20512, 'Black Hawk Elbow Pads', 'Elbow pads, pair', 1019, NULL, 8, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (30321, 'Grand Prix Bicycle', 'Road bicycle', 828, 1291, 1669, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (30326, 'Himalaya Bicycle', 'Mountain bicycle', 833, 1296, 582, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (30421, 'Grand Prix Bicycle Tires', 'Road bicycle tires', 927, NULL, 16, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (30433, 'New Air Pump', 'Tire pump', 940, NULL, 20, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (32779, 'Slaker Water Bottle', 'Mater bottle', 1286, NULL, 7, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (32861, 'Safe-T Helmet', 'Bicycle helmet', 1368, 1829, 60, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (40421, 'Alexeyer Pro Lifting Bar', 'Straight bar', 928, 1381, 65, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (40422, 'Pro Curling Bar', 'Curling bar', 929, 1382, 50, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (41010, 'Prostar 10 Pound Weight', 'Ten pound weight', 517, NULL, 8, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (41020, 'Prostar 20 Pound Weight', 'Twenty pound weight', 527, NULL, 12, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (41050, 'Prostar 50 Pound Weight', 'Fifty pound weight', 557, NULL, 25, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (41080, 'Prostar 80 Pound Weight', 'Eighty pound weight', 587, NULL, 35, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50417, 'Griffey Glove', 'Outfielders glove', 924, 1367, 80, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50418, 'Alomar Glove', 'Infielders glove', 925, 1368, 75, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50419, 'Steinbach Glove', 'Catchers glove', 926, 1369, 80, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50530, 'Cabrera Bat', 'Thirty inch bat', 1037, 1480, 45, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50532, 'Puckett Bat', 'Thirty-two inch bat', 1039, 1482, 47, NULL)

    INTO S_PRODUCT (ID, NAME, SHORT_DESC, LONGTEXT_ID, IMAGE_ID, SUGGESTED_WHLSL_PRICE, WHLSL_UNITS)
    VALUES (50536, 'Winfield Bat', 'Thirty-six inch bat', 1043, 1486, 50, NULL)
(SELECT * FROM DUAL);


-- TABLE: S_REGION
INSERT ALL
    INTO S_REGION (ID, NAME)
    VALUES (1, 'USA')

    INTO S_REGION (ID, NAME)
    VALUES (2, 'S.America')

    INTO S_REGION (ID, NAME)
    VALUES (3, 'Africa')

    INTO S_REGION (ID, NAME)
    VALUES (4, 'Aziya')

    INTO S_REGION (ID, NAME)
    VALUES (5, 'Europe')

    INTO S_REGION (ID, NAME)
    VALUES (6, 'Central America')
(SELECT * FROM DUAL);


-- TABLE: S_SALGRADE
INSERT ALL
    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (1, 700, 1200)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (2, 1201, 1400)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (3, 1401, 2000)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (4, 2001, 3000)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (5, 3001, 9999)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (1, 700, 1200)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (2, 1201, 1400)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (3, 1401, 2000)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (4, 2001, 3000)

    INTO S_SALGRADE (GRADE, LOSAL, HISAL)
    VALUES (5, 3001, 9999)
(SELECT * FROM DUAL);


-- TABLE: S_TITLE
INSERT ALL
    INTO S_TITLE (TITLE)
    VALUES ('President')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Operations')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Sales')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Finance')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Administration')

    INTO S_TITLE (TITLE)
    VALUES ('Warehouse Manager')

    INTO S_TITLE (TITLE)
    VALUES ('Uarehouse Hanager')

    INTO S_TITLE (TITLE)
    VALUES ('Uarehouse Nanager')

    INTO S_TITLE (TITLE)
    VALUES ('Warehouse Manager')

    INTO S_TITLE (TITLE)
    VALUES ('Sales Representative')

    INTO S_TITLE (TITLE)
    VALUES ('Stock Clerk')

    INTO S_TITLE (TITLE)
    VALUES ('President')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Operations')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Sales')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Finance')

    INTO S_TITLE (TITLE)
    VALUES ('VP, Administration')

    INTO S_TITLE (TITLE)
    VALUES ('Warehouse Manager')

    INTO S_TITLE (TITLE)
    VALUES ('Uarehouse Hanager')

    INTO S_TITLE (TITLE)
    VALUES ('Uarehouse Nanager')

    INTO S_TITLE (TITLE)
    VALUES ('Warehouse Manager')

    INTO S_TITLE (TITLE)
    VALUES ('Sales Representative')

    INTO S_TITLE (TITLE)
    VALUES ('Stock Clerk')
(SELECT * FROM DUAL);

COMMIT;
